debug: false
reportSize: 10
mostCommonMobsSize: 3

worlds:

  default:
    rate: 1 
    include:
    exclude:
      
  world:
    base:
      active: false
      rate: 0.9
      include: ALL
      exclude:
      chunks:
      - {x: 0, z: 30}
      
    example_rule_1:
      active: false
      rate: 0.5
      include:
      exclude:
      - BAT
      chunks:
      - {x: 0, z: 0}
