name: MobControl
main: pt.minecraft.mobcontrol.MobControlPlugin
version: 0.0.1
description: Limit mob spawning on a chunk basis
author: [disco]
commands:
   mobprofiler:
      description: This command profiles mob spawn events.
      usage: /<command> (start|stop|reset|chunk|report [world])